version: "3.9"

services:
  tkh.web:
    container_name: tkh_web_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: >
        Host=tkh.db;
        Port=5432;
        Database=TKHDb;
        Username=tkh_user;
        Password=StrongPostgresPass123!
      Serilog__WriteTo__0__Args__serverUrl: "http://tkh.seq:5341"
    depends_on:
      tkh.db:
        condition: service_healthy
      tkh.seq:
        condition: service_started
    restart: always

  tkh.db:
    container_name: tkh_postgres_db
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: tkh_user
      POSTGRES_PASSWORD: StrongPostgresPass123!
      POSTGRES_DB: TKHDb
    ports:
      - "5434:5432"
    volumes:
      - tkh_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tkh_user -d TKHDb -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always

  tkh.seq:
    container_name: tkh_seq
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=StrongSeqPass123!
    ports:
      - "8090:80"
      - "5342:5341"
    volumes:
      - tkh_seq_data:/data
    restart: always

volumes:
  tkh_db_data:
  tkh_seq_data:
