version: "3.9"

services:
  tkh.web:
    container_name: tkh_web_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: >
        Host=tkh.db;
        Port=5432;
        Database=TKHDb;
        Username=tkh_user;
        Password=StrongPostgresPass123!
    depends_on:
      tkh.db:
        condition: service_healthy
    restart: always

  tkh.db:
    container_name: tkh_postgres_db
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: tkh_user
      POSTGRES_PASSWORD: StrongPostgresPass123!
      POSTGRES_DB: TKHDb
    ports:
      - "5434:5432"
    volumes:
      - tkh_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tkh_user -d TKHDb -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always

volumes:
  tkh_db_data:
